/* Runtime hooks keep new build/event rules separate from the original campaign. */
window.NeonExpansion=(()=>{
 const D=NeonExpansionData,T=Math.PI*2,roomNames={fountain:'霓虹许愿池',workshop:'义体改造室',altar:'契约祭坛'},images={},effects=[];
 let api,p,s,random,uiClock=0,healCD=0,hitCount=0,killCount=0,seed=0,modal,readout,panel,log='';
 for(const id of ['fountain','workshop','altar','relic-icons']){const im=new Image();im.src='assets/expansion/'+id+'.png';images[id]=im;}
 const has=id=>p.items.includes(id),buff=id=>(p.buffs?.[id]||0)>0;
 function install(a){api=a;p=a.player;s=a.state;modal=document.createElement('section');modal.id='event-modal';modal.hidden=true;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','特殊房间交易');a.shell.append(modal);readout=document.createElement('div');readout.id='buff-readout';a.shell.append(readout);panel=document.createElement('div');panel.id='build-readout';document.querySelector('#pause-screen').append(panel);
  addEventListener('keydown',e=>{if(s.mode==='event'){if(e.code==='Escape')close();e.preventDefault();e.stopImmediatePropagation();return}if(e.code==='KeyR'&&!e.repeat&&s.mode==='playing'&&roomNames[s.room?.type]&&Math.hypot(p.x-640,p.y-350)<160){open();e.preventDefault();e.stopImmediatePropagation()}},{capture:true});
 }
 function reset(){seed=(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0;random=D.rng(seed);p.buffs={};p.modifiers={};healCD=hitCount=killCount=0;effects.length=0;log='';if(modal)modal.hidden=true;}
 function floor(){D.addBranch(s.rooms,s.floor,seed);}
 function stats(v){const m=p.modifiers||{};v.damage*= (buff('power')?1.3:1)*(has('aegis-charge')&&p.shield===p.maxShield&&p.shield>0?1.2:1)*(m.damage||1);v.delay*= (buff('surge')?.75:1)*(has('redline')&&p.hp<=p.maxHp*.5?.75:1)*(has('aegis-charge')&&p.shield<p.maxShield?.9:1)*(m.delay||1);v.delay=Math.max(.065,v.delay);v.critChance=p.critOverride??Math.min(.75,v.critChance+(buff('focus')?.2:0)+(has('martyr')?.1:0));v.pierce=Math.min(7,v.pierce+(buff('pierce')?2:0));v.range*=m.range||1;return v}
 function speed(){return(buff('haste')?1.2:1)*(p.modifiers?.move||1)}
 function grant(id){p.buffs[id]=D.buffs[id].duration;refresh();api.toast(D.buffs[id].name+' // '+D.buffs[id].desc)}
 function take(item){if(item.id==='martyr'){p.maxHp=Math.max(2,p.maxHp-1);p.hp=Math.min(p.hp,p.maxHp)}refresh();const names=D.active(p.items).filter(r=>r[1].includes(item.id));if(names.length)api.toast('联动激活 // '+names.map(r=>r[0]).join(' · '));}
 function applied(e,t){if(!t||t.secondary||e.dead||t.owner==='drone'&&!has('shared-bus'))return;if(has('conductive'))e.marked=4;
  if(has('ember')){e.burn=3;e.burnDamage=Math.max(e.burnDamage||0,t.damage*.2);e.burnTick=e.burnTick??.5;}
  if(has('flashpoint')&&e.burn>0){e.heat=(e.heat||0)+1;if(e.heat>=5){e.heat=0;blast(e.x,e.y,105,t.damage*1.2,'#ffae65')}}
  if(has('capacitor')&&++hitCount%6===0)arc(e,t.damage*.8,1);
 }
 function hitScale(e,t){return has('kinetic')&&t?.ricochetCount>0?1.2:1}
 function beam(x,y,x2,y2,color){if(effects.length<48)effects.push({kind:'beam',x,y,x2,y2,color,life:.16,max:.16})}
 function secondary(e,damage){api.damage(e,damage,{secondary:true,damage,crit:false,form:'vanguard',color:'#a4edff',vx:1,vy:0})}
 function arc(from,damage,count=has('arc-relay')?2:1){const visited=new Set([from.uid]);let prev=from;for(let i=0;i<count;i++){const next=s.enemies.filter(e=>!e.dead&&!visited.has(e.uid)&&Math.hypot(e.x-prev.x,e.y-prev.y)<(has('arc-relay')?240:180)&&api.lineClear(prev,e)).sort((a,b)=>(b.marked>0?1:0)-(a.marked>0?1:0)||Math.hypot(a.x-prev.x,a.y-prev.y)-Math.hypot(b.x-prev.x,b.y-prev.y))[0];if(!next)break;visited.add(next.uid);secondary(next,damage);beam(prev.x,prev.y,next.x,next.y,'#82ffff');prev=next;}}
 function blast(x,y,r,damage,color){if(effects.length<48)effects.push({kind:'ring',x,y,r,color,life:.32,max:.32});for(const e of [...s.enemies])if(!e.dead&&Math.hypot(e.x-x,e.y-y)<r&&api.lineClear({x,y},e))secondary(e,damage)}
 function bounce(t){if(has('kinetic')){t.vx*=1.15;t.vy*=1.15}if(has('wall-split')&&!t.branch&&t.ricochetCount===1&&s.tears.length<100){const a=Math.atan2(t.vy,t.vx);for(const side of [-1,1])api.spawn(t.x,t.y,a+side*.38,{speed:Math.hypot(t.vx,t.vy),range:320,size:Math.max(4,t.r*.75),damage:t.damage*.45,pierce:0,ricochets:1,critChance:0,branch:true});}}
 function steer(t,dt){if(has('rebound-aim')&&t.ricochetCount>0){const e=s.enemies.filter(e=>!e.dead&&api.lineClear(t,e)).sort((a,b)=>Math.hypot(a.x-t.x,a.y-t.y)-Math.hypot(b.x-t.x,b.y-t.y))[0];if(e){const a=Math.atan2(t.vy,t.vx),target=Math.atan2(e.y-t.y,e.x-t.x),d=Math.atan2(Math.sin(target-a),Math.cos(target-a)),q=a+Math.max(-1.6*dt,Math.min(1.6*dt,d)),speed=Math.hypot(t.vx,t.vy);t.vx=Math.cos(q)*speed;t.vy=Math.sin(q)*speed}}}
 function killed(e){if(e.boss)return;if((has('ash-leech')&&e.burn>0||buff('siphon'))&&healCD<=0){p.hp=Math.min(p.maxHp,p.hp+1);healCD=buff('siphon')?8:12}if(has('bloodbank')&&++killCount%12===0)p.hp=Math.min(p.maxHp,p.hp+1)}
 function hurt(oldShield){if(has('shield-coil')&&oldShield>0&&p.shield===0){p.invuln=Math.max(p.invuln,1.5);s.enemyBullets=s.enemyBullets.filter(b=>Math.hypot(b.x-p.x,b.y-p.y)>145);blast(p.x,p.y,145,12*(2**(s.floor-1)),'#86edff')}}
 function clear(){if(has('repair-loop'))p.shield=Math.min(p.maxShield,p.shield+1);if(random()<.2)grant(Object.keys(D.buffs)[Math.floor(random()*6)])}
 function update(dt){healCD=Math.max(0,healCD-dt);for(const id of Object.keys(p.buffs||{}))p.buffs[id]=Math.max(0,p.buffs[id]-dt);for(const e of [...s.enemies]){e.marked=Math.max(0,(e.marked||0)-dt);if(e.burn>0){e.burn=Math.max(0,e.burn-dt);e.burnTick-=dt;if(e.burnTick<=0){e.burnTick+=.5;secondary(e,(e.burnDamage||0)*.5)}}}for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0)effects.splice(i,1)}uiClock-=dt;if(uiClock<=0){uiClock=.15;refresh()}}
 function refresh(){const list=Object.entries(p.buffs||{}).filter(([,t])=>t>0);readout.innerHTML=list.map(([id,t])=>`<span style="--buff:${D.buffs[id].color}" title="${D.buffs[id].desc}">${D.buffs[id].name} <b>${Math.ceil(t)}s</b></span>`).join('');const links=D.recipes.map(([name,ids,desc])=>{const n=ids.filter(has).length;return `<div class="${n===ids.length?'linked':''}"><b>${name} ${n}/${ids.length}</b><small>${desc}</small><span>${ids.map(id=>{const item=api.items.find(x=>x.id===id);return(has(id)?'✓ ':'○ ')+(item?.name||id)}).join(' + ')}</span></div>`}).join('');const buffs=list.map(([id,t])=>`${D.buffs[id].name} ${Math.ceil(t)}s：${D.buffs[id].desc}`).join(' / ');panel.innerHTML='<h3>神经构筑 · 已点亮的节点</h3>'+links+'<p>'+buffs+'</p>';}
 function icon(ctx,item,size){if(item.icon===undefined||!images['relic-icons'].naturalWidth)return false;const im=images['relic-icons'],w=im.naturalWidth/6,h=im.naturalHeight/3;ctx.drawImage(im,item.icon%6*w,Math.floor(item.icon/6)*h,w,h,-size,-size,size*2,size*2);return true;}
 function draw(ctx,layer='effects'){if(layer==='room'&&roomNames[s.room?.type]){const im=images[s.room.type],x=640,y=350;ctx.save();ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(x,y+46,91,30,0,0,T);ctx.fill();if(im.naturalWidth)ctx.drawImage(im,x-125,y-160,250,250);ctx.fillStyle='#b7fff5';ctx.textAlign='center';ctx.font='bold 15px Microsoft YaHei';ctx.fillText(roomNames[s.room.type],x,y+157);ctx.font='12px Microsoft YaHei';ctx.fillText(Math.hypot(p.x-x,p.y-y)<160?'R 交互 · 明示代价后确认':'靠近装置按 R 交互',x,y+178);ctx.restore()}
  if(layer==='room')return;for(const e of s.enemies){if(!e.marked&&!e.burn)continue;ctx.save();ctx.strokeStyle=e.burn>0?'#ffae65':'#7dffff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r+8,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.restore()}
  for(const fx of effects){ctx.save();ctx.strokeStyle=fx.color;ctx.globalAlpha=fx.life/fx.max;ctx.lineWidth=3;ctx.beginPath();if(fx.kind==='beam'){ctx.moveTo(fx.x,fx.y);ctx.lineTo(fx.x2,fx.y2)}else ctx.arc(fx.x,fx.y,Math.max(1,fx.r*(1-fx.life/fx.max)),0,T);ctx.stroke();ctx.restore()}}
 function close(){modal.hidden=true;if(s.mode==='event')s.mode='playing';api.clearInput();}
 function open(){if(!roomNames[s.room?.type])return;api.clearInput();s.mode='event';modal.hidden=false;show();modal.querySelector('button')?.focus()}
 function show(){const room=s.room,event=room.event,type=room.type,cost=6+s.floor+event.uses*3;let choices=[];
  if(type==='fountain')choices=['攻击','防御','资源'].map((name,i)=>({id:String(i),name:'许愿 · '+name,desc:`消耗 ${cost} DATA · ${event.misses>=2?'本次保底遗物':'25% 遗物 / 45% 祝福 / 30% 补给'}。`,disabled:event.uses>=3||p.coins<cost}));
  if(type==='workshop')choices=[{id:'caliber',name:'重型枪膛',desc:'伤害 ×1.35，射击间隔 ×1.15。'},{id:'trigger',name:'短管快射',desc:'射击间隔 ×0.75，射程 ×0.75。'},{id:'shell',name:'装甲义体',desc:'护盾上限 +2 并补满，移动速度 ×0.90。'}].map(c=>({...c,disabled:event.taken}));
  if(type==='altar')choices=[{id:'blood',name:'献出一格核心',desc:'最大生命 -1（至少保留 2）；获得一件稀有遗物。',disabled:event.taken||p.maxHp<=2},{id:'burden',name:'背负迟滞契约',desc:'移动速度永久 ×0.88；获得一件稀有遗物。',disabled:event.taken}];
  modal.innerHTML=`<div class="event-card"><div class="event-kicker">SIDE PROTOCOL // ${s.floor}</div><h2>${roomNames[type]}</h2><p>DATA ${p.coins} · 核心 ${p.hp}/${p.maxHp}${type==='fountain'?` · 已许愿 ${event.uses}/3 · 连续非遗物 ${event.misses}`:''}</p><div class="event-options">${choices.map(c=>`<button data-event-choice="${c.id}" ${c.disabled?'disabled':''}><b>${c.name}</b><span>${c.desc}</span></button>`).join('')}</div><p class="event-result" role="status">${event.result||'所有代价都在确认前展示。可以直接离开，不影响通关。'}</p><button id="event-close">离开装置 · ESC</button></div>`;
  modal.querySelector('#event-close').onclick=close;for(const el of modal.querySelectorAll('[data-event-choice]'))el.onclick=()=>choose(el.dataset.eventChoice);
 }
 function choose(id){if(s.mode!=='event')return false;const e=s.room.event,type=s.room.type;if(type==='fountain'){const cost=6+s.floor+e.uses*3;if(e.uses>=3||p.coins<cost)return false;const roll=D.rng(e.seed+e.uses*103)(),kind=D.wish(e.uses,e.misses,roll),direction=Number(id);if(![0,1,2].includes(direction))return false;const candidates=api.items.filter(i=>i.minFloor<=s.floor&&!has(i.id)&&(direction===0?['weapon','core'].includes(i.category):direction===1?['shield','risk'].includes(i.build)||['cyberheart','blackbox','magnet'].includes(i.id):true));if(kind==='relic'&&!candidates.length){e.result='该方向遗物已全部获得。未扣费，请换个方向。';show();return false}p.coins-=cost;e.uses++;if(kind==='relic'){e.misses=0;const item=candidates[Math.floor(D.rng(e.seed+e.uses*89)()*candidates.length)];api.take(item);e.result='许愿回应：'+item.name;}else{e.misses++;if(kind==='buff'){const pools=[['power','surge','pierce'],['haste','siphon','focus'],Object.keys(D.buffs)],pool=pools[direction],id=pool[Math.floor(roll*17)%pool.length];grant(id);e.result='临时祝福：'+D.buffs[id].name+' · '+D.buffs[id].duration+' 秒（关闭界面后计时）'}else{if(direction===1){p.shield=Math.min(p.maxShield,p.shield+2);p.hp=Math.min(p.maxHp,p.hp+1);e.result='恢复 1 电池格、2 层护盾'}else{p.coins+=4;p.bombs++;e.result='获得 4 DATA 与 1 枚炸弹'}}}}
  else if(type==='workshop'){if(e.taken||!['caliber','trigger','shell'].includes(id))return false;e.taken=true;const m=p.modifiers;if(id==='caliber'){m.damage=(m.damage||1)*1.35;m.delay=(m.delay||1)*1.15}else if(id==='trigger'){m.delay=(m.delay||1)*.75;m.range=(m.range||1)*.75}else{p.maxShield+=2;p.shield=p.maxShield;m.move=(m.move||1)*.9}e.result='改造完成，本局持续；另外两项已封存。'}
  else if(type==='altar'){if(e.taken||!['blood','burden'].includes(id)||id==='blood'&&p.maxHp<=2)return false;const pool=api.items.filter(i=>i.rarity==='rare'&&i.minFloor<=s.floor&&!has(i.id));if(!pool.length){e.result='本层稀有遗物已获得完毕，未收取代价。';show();return false}e.taken=true;if(id==='blood'){p.maxHp--;p.hp=Math.min(p.hp,p.maxHp)}else p.modifiers.move=(p.modifiers.move||1)*.88;const item=pool[Math.floor(D.rng(e.seed)()*pool.length)];api.take(item);e.result='契约成立：获得 '+item.name+'，代价本局持续。'}else return false;
  log=e.result;api.toast(e.result);api.refresh();show();return true;
 }
 return{install,reset,floor,stats,speed,take,applied,hitScale,bounce,steer,killed,hurt,clear,update,draw,icon,arc,grant,open,close,roomNames,buff,has,debug:()=>({seed,buffs:{...p.buffs},modifiers:{...p.modifiers},active:D.active(p.items).map(r=>r[0]),log,event:s.room.event?{...s.room.event}:null}),choose,images};
})();
