/* Original art library for the six-floor room campaign. */
window.NeonLegacyArt=(()=>{
 const images={},heroes=['vanguard','wraith','beast','seraph'],bosses=['cherub','matriarch','hexa','furnace','reaper','sovereign'];
 for(const id of [...heroes.map(v=>'hero-'+v),...bosses.map(v=>'boss-'+v),'weapons','enemies','menu-city','arena-floor','hero-motion',...bosses.map(v=>'phase2-'+v)]){const im=new Image();im.src='assets/generated/'+id+'.webp';images[id]=im}
 const ready=id=>images[id]?.complete&&images[id]?.naturalWidth;
 function draw(ctx,id,x,y,w,h=w,tilt=0,flip=1){if(!ready(id))return false;ctx.save();ctx.translate(x,y);ctx.rotate(tilt);ctx.scale(flip,1);const aspect=images[id].naturalWidth/images[id].naturalHeight,dw=w*Math.min(1,aspect),dh=h*Math.min(1,1/aspect);ctx.drawImage(images[id],-dw/2,-dh/2,dw,dh);ctx.restore();return true}
 function cell(ctx,id,i,cols,rows,x,y,w,h=w,angle=0){if(!ready(id))return;const im=images[id],sw=im.naturalWidth/cols,sh=im.naturalHeight/rows;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(im,i%cols*sw,Math.floor(i/cols)*sh,sw,sh,-w/2,-h/2,w,h);ctx.restore()}
 function shadow(ctx,x,y,r){ctx.save();ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(x,y+15,r,r*.32,0,0,Math.PI*2);ctx.fill();ctx.restore()}
 function playerBase(ctx,p,time){if(!ready('hero-'+p.form))return false;shadow(ctx,p.x,p.y,22);const walking=Math.hypot(p.x-p.prevX,p.y-p.prevY)>.3,cycle=walking?Math.sin(time*13):Math.sin(time*2)*.3;ctx.save();ctx.globalAlpha=p.invuln>0?.58+.42*Math.abs(Math.sin(time*24)):1;if(ready('hero-motion')){ctx.save();ctx.translate(p.x,p.y-12+cycle*2);ctx.scale(p.aimX<0?-1:1,1);cell(ctx,'hero-motion',heroes.indexOf(p.form)*4+(walking?1+Math.floor(time*8)%2:p.recoil>0?3:0),4,4,0,0,88,88,cycle*.025);ctx.restore()}else draw(ctx,'hero-'+p.form,p.x,p.y-12+cycle*2,85,85,cycle*.035,p.aimX<0?-1:1);ctx.restore();const angle=Math.atan2(p.aimY,p.aimX),wi=heroes.indexOf(p.form),recoil=p.recoil||0;cell(ctx,'weapons',wi,4,3,p.x+Math.cos(angle)*(25-recoil),p.y+Math.sin(angle)*(25-recoil),45,35,angle);if(p.invuln>0){ctx.save();ctx.strokeStyle='#ade6df77';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,30,0,Math.PI*2);ctx.stroke();ctx.restore()}return true}
 function player(ctx,p,time){ctx.save();ctx.translate(p.x,p.y);ctx.scale(1.25,1.25);ctx.translate(-p.x,-p.y);const ok=playerBase(ctx,p,time);ctx.restore();return ok;}
 function enemy(ctx,e,time){if(!ready('enemies'))return false;const i={crawler:0,charger:1,shooter:2,turret:3,drone:4}[e.type]??4;shadow(ctx,e.x,e.y,e.r*.8);const size=e.r*(e.elite?4.4:3.8);cell(ctx,'enemies',i,3,2,e.x,e.y-7+Math.sin(time*7+(e.uid||0))*2,size,size,e.type==='turret'?0:Math.sin(time*7)*.035);if(e.elite){ctx.save();ctx.strokeStyle='#e7c481';ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.beginPath();ctx.arc(e.x,e.y,e.r+9,0,Math.PI*2);ctx.stroke();ctx.restore()}return true}
 function boss(ctx,b,time,floor){const id=bosses[Math.max(0,Math.min(5,floor-1))];if(!ready('boss-'+id))return false;shadow(ctx,b.x,b.y,b.r);const size=b.r*3.6,entry=Math.max(0,(b.entryTime??2.2)/2.2),bob=Math.sin(time*2.5)*4-400*entry*entry;draw(ctx,(b.phase>0&&ready('phase2-'+id)?'phase2-':'boss-')+id,b.x,b.y-20+bob,size,size,Math.sin(time*1.7)*.035);ctx.save();ctx.strokeStyle=b.color;ctx.globalAlpha=.35;ctx.lineWidth=2;if(b.phase>0){ctx.beginPath();ctx.ellipse(b.x,b.y+15,b.r*1.5,b.r*.7,0,0,Math.PI*2);ctx.stroke()}if(b.warning>0||b.invuln>0){ctx.globalAlpha=.55+.2*Math.sin(time*20);ctx.strokeStyle='#f7d493';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r*1.55,0,Math.PI*2);ctx.stroke()}ctx.restore();return true}
 const intro=document.getElementById('boss-intro'),portraitCanvas=document.createElement('canvas');portraitCanvas.width=560;portraitCanvas.height=590;portraitCanvas.id='legacy-portrait-rig';intro.append(portraitCanvas);const portraitCtx=portraitCanvas.getContext('2d');
 function portrait(){if(!intro.classList.contains('visible'))return;const el=document.getElementById('legacy-boss-portrait'),name=el.src.split('/').pop().replace('.webp','');portraitCtx.clearRect(0,0,560,590);if(window.NeonNewBosses?.intro(portraitCtx,intro.dataset.expansion,performance.now()/1000))return;if(window.NeonBossArt?.intro(portraitCtx,Number(intro.dataset.floor),performance.now()/1000))return;window.NeonPortraitRig?.draw(portraitCtx,images[name],280,295,550,570,performance.now()/1000)}
 return{player,enemy,boss,images,bosses,ready,portrait};
})();
